[package]
name = "writing-trainer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
ts-rs = "11.0.1"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"

[features]
default = []
wasm-support = []
