[workspace]
resolver = "2"
members = [
    "./rust_packages/backend",
    "./rust_packages/core",
    "./rust_packages/wasm"
]

[profile.release]
opt-level = 'z'
codegen-units = 1
lto = true
strip = true
panic = "abort"
