FROM debian:12-slim
USER root

# Required for using the correct GLIBC (v2.38)
RUN echo 'deb http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y libssl-dev ca-certificates sqlite3 glibc-doc

RUN useradd -m -s /bin/bash rust \
  && mkdir -p /app \
  && chown -R rust:rust /app

USER rust
WORKDIR /app

COPY --chown=rust:rust target/release/writing-trainer-backend .

CMD ./writing-trainer-backend
