[package]
name = "writing-trainer-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"
js-sys = "0.3.76"
rexie = "0.6.2"
wasm-bindgen = "0.2.99"
web-sys = "0.3.76"
writing-trainer-core = { version = "0.1.0", path = "../core" }

[lib]
crate-type = ["cdylib", "rlib"]
