pub const ENV_LOGGER_LEVEL: &str = "LOGGER_LEVEL";
pub const ENV_GOOGLE_OAUTH_REDIRECT_URL: &str = "NEXT_PUBLIC_BACKEND_URL";
pub const ENV_GOOGLE_CLIENT_ID: &str = "NEXT_PUBLIC_GOOGLE_CLIENT_ID";

pub const ENV_CLIENT_ORIGIN: &str = "CLIENT_ORIGIN";
pub const ENV_DATABASE_URL: &str = "DATABASE_URL";
pub const ENV_GOOGLE_CLIENT_SECRET: &str = "GOOGLE_CLIENT_SECRET";
pub const ENV_JWT_SECRET: &str = "JWT_SECRET";
pub const ENV_TOKEN_EXPIRED_IN: &str = "TOKEN_EXPIRED_IN";
pub const ENV_TOKEN_MAXAGE: &str = "TOKEN_MAXAGE";
