name: Debug
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
