name: Deploy Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'packages.json'
      - 'package-lock.json'
      - 'src/react-ui/**'
      - 'src/core/**'
      - 'src/web-app/**'
      - 'src/pages/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.repository == 'igncp/writing-trainer' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install 🚧
        run: |
          touch ./is-ci-nodejs
          nix develop path:$(pwd) -c npm install

      - name: Build and publish docker image
        run: |
          cp .env.example .env
          nix develop path:$(pwd) -c bash -c scripts/ci/build_docker_frontend.sh
        env:
          NEXT_PUBLIC_BACKEND_URL: 'https://api.learn-languages-writing.com'
